/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package jessy.shipgirlcombatsystem.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ThriftCommandEnum implements org.apache.thrift.TEnum {
  Advance(0),
  TurnLeft(1),
  TurnRight(2),
  DriftN(3),
  DriftNE(4),
  DriftSE(5),
  DriftS(6),
  DriftSW(7),
  DriftNW(8);

  private final int value;

  private ThriftCommandEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ThriftCommandEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return Advance;
      case 1:
        return TurnLeft;
      case 2:
        return TurnRight;
      case 3:
        return DriftN;
      case 4:
        return DriftNE;
      case 5:
        return DriftSE;
      case 6:
        return DriftS;
      case 7:
        return DriftSW;
      case 8:
        return DriftNW;
      default:
        return null;
    }
  }
}
