/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jessy.shipgirlcombatsystem.ship.systems;

import java.awt.Color;

/**
 *
 * @author dirk
 */
public class WeaponPanel extends javax.swing.JPanel {
    public final static Color normalBackground = new Color(238,238,238);
    public final static Color damagedBackground = Color.RED;
    public final static Color readyBackground = Color.GREEN;
    public final static Color usedBackground = Color.YELLOW;

    /**
     * Creates new form WeaponPanel
     */
    public WeaponPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fireButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Weapon"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jessy/shipgirlcombatsystem/images/arc/Full.png"))); // NOI18N

        fireButton.setText("Fire");
        fireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(fireButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel1)
            .addComponent(fireButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireButtonActionPerformed
        // TODO add your handling code here:
        this.setBackground(usedBackground);
    }//GEN-LAST:event_fireButtonActionPerformed

    public void setDamaged(boolean state) {
        fireButton.setEnabled(!state);
        if(state) {
            this.setBackground(damagedBackground);
        } else {
            this.setBackground(normalBackground);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fireButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
