/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jessy.shipgirlcombatsystem.screens;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import jessy.shipgirlcombatsystem.commands.ShipCommands;
import jessy.shipgirlcombatsystem.map.Direction;
import jessy.shipgirlcombatsystem.ship.Ship;

/**
 *
 * @author dirk
 */
public class ShipPanel extends javax.swing.JPanel {

    Ship currentShip;
    JFrame windowContainer;
    /**
     * Creates new form ShipWindow
     */
    public ShipPanel() {
        initComponents();
    }
    
    public void updateShip(final Ship ship) {
        currentShip = ship;
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                shipNameField.setText(ship.getName());
                speedNLabel.setText("" + (-ship.getSpeedR()));
                speedSWLabel.setText("" + (ship.getSpeedQ()));
                windowContainer.setVisible(true);
                requestFocus();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        shipNameField = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        speedNLabel = new javax.swing.JLabel();
        speedNWLabel = new javax.swing.JLabel();
        speedSWLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        upButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        shipNameField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        shipNameField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jessy/shipgirlcombatsystem/images/BaseShip.png"))); // NOI18N
        shipNameField.setText("ShipName");
        shipNameField.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shipNameField.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(shipNameField, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Speed"));
        jPanel1.setMinimumSize(new java.awt.Dimension(60, 90));
        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        speedNLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jessy/shipgirlcombatsystem/images/ArrowN.png"))); // NOI18N
        speedNLabel.setText("0");
        speedNLabel.setIconTextGap(14);
        speedNLabel.setMaximumSize(new java.awt.Dimension(66, 22));
        speedNLabel.setMinimumSize(new java.awt.Dimension(66, 22));
        speedNLabel.setPreferredSize(new java.awt.Dimension(66, 22));
        jPanel1.add(speedNLabel);

        speedNWLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jessy/shipgirlcombatsystem/images/ArrowNW.png"))); // NOI18N
        speedNWLabel.setText("0");
        speedNWLabel.setMaximumSize(new java.awt.Dimension(66, 16));
        speedNWLabel.setMinimumSize(new java.awt.Dimension(66, 16));
        speedNWLabel.setPreferredSize(new java.awt.Dimension(66, 16));
        jPanel1.add(speedNWLabel);

        speedSWLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jessy/shipgirlcombatsystem/images/ArrowSW.png"))); // NOI18N
        speedSWLabel.setText("0");
        speedSWLabel.setPreferredSize(new java.awt.Dimension(66, 18));
        jPanel1.add(speedSWLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thrusters"));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel2.setLayout(new java.awt.GridLayout(4, 3));
        jPanel2.add(jLabel1);

        upButton.setText("up");
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });
        jPanel2.add(upButton);
        jPanel2.add(jLabel3);

        jButton2.setText("side");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jPanel2.add(jLabel4);

        jButton3.setText("side");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setText("side");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jPanel2.add(jLabel5);

        jButton6.setText("side");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jPanel2.add(jLabel6);

        jButton5.setText("down");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jPanel2.add(jLabel7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Main Engine"));
        jPanel3.setLayout(new java.awt.GridLayout(2, 3));
        jPanel3.add(jLabel2);

        jButton1.setText("forward");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jPanel3.add(jLabel8);

        jButton7.setText("turn Left");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jPanel3.add(jLabel9);

        jButton8.setText("turn Right");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.SOUTHEAST));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        MapPanel.getInstance().addCommand(ShipCommands.turnLeft(currentShip));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        MapPanel.getInstance().addCommand(ShipCommands.turnRight(currentShip));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MapPanel.getInstance().addCommand(ShipCommands.moveForward(currentShip));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.NORTH));
        updateShip(currentShip);
    }//GEN-LAST:event_upButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // currentShip.drift(Direction.NORTHEAST);
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.NORTHEAST));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     //  currentShip.drift(Direction.NORTHWEST);
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.NORTHWEST));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      //  currentShip.drift(Direction.SOUTH);
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.SOUTH));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       // currentShip.drift(Direction.SOUTHWEST);
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.SOUTHWEST));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel shipNameField;
    private javax.swing.JLabel speedNLabel;
    private javax.swing.JLabel speedNWLabel;
    private javax.swing.JLabel speedSWLabel;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables
}
