/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jessy.shipgirlcombatsystem.screens;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import jessy.shipgirlcombatsystem.commands.ShipCommands;
import jessy.shipgirlcombatsystem.map.Direction;
import jessy.shipgirlcombatsystem.ship.IShipSystem;
import jessy.shipgirlcombatsystem.ship.Ship;
import jessy.shipgirlcombatsystem.util.Phase;

/**
 *
 * @author dirk
 */
public class ShipPanel extends javax.swing.JPanel {

    Ship currentShip;
    JFrame windowContainer;
    /**
     * Creates new form ShipWindow
     */
    public ShipPanel() {
        initComponents();
    }
    
    public void updateShip(final Ship ship) {
        currentShip = ship;
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                shipNameField.setText(ship.getName());
                speedNLabel.setText("" + (-ship.getSpeedR()));
                speedSWLabel.setText("" + (ship.getSpeedQ()));
                windowContainer.setVisible(true);
                if(MapPanel.getInstance().getBoard().getPhase() == Phase.ACTION_PHASE) {
                    tabbedPanel.setSelectedIndex(1);
                } else {
                    tabbedPanel.setSelectedIndex(0);
                }
                actionPanel.removeAll();
                for(IShipSystem item : ship.getEquipment()) {
                    actionPanel.add(item.getSystemPanel());
                }
                damageLabel.setText(ship.getStatusString());
                requestFocus();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        shipNameField = new javax.swing.JLabel();
        tabbedPanel = new javax.swing.JTabbedPane();
        movementPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        speedNLabel = new javax.swing.JLabel();
        speedNWLabel = new javax.swing.JLabel();
        speedSWLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        upButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        actionTabPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actionPanel = new javax.swing.JPanel();
        damageLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        shipNameField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        shipNameField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jessy/shipgirlcombatsystem/images/BaseShip.png"))); // NOI18N
        shipNameField.setText("ShipName");
        shipNameField.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        shipNameField.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(shipNameField, gridBagConstraints);

        movementPanel.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Speed"));
        jPanel5.setMinimumSize(new java.awt.Dimension(60, 90));
        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        speedNLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jessy/shipgirlcombatsystem/images/ArrowN.png"))); // NOI18N
        speedNLabel.setText("0");
        speedNLabel.setIconTextGap(14);
        speedNLabel.setMaximumSize(new java.awt.Dimension(66, 22));
        speedNLabel.setMinimumSize(new java.awt.Dimension(66, 22));
        speedNLabel.setPreferredSize(new java.awt.Dimension(66, 22));
        jPanel5.add(speedNLabel);

        speedNWLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jessy/shipgirlcombatsystem/images/ArrowNW.png"))); // NOI18N
        speedNWLabel.setText("0");
        speedNWLabel.setMaximumSize(new java.awt.Dimension(66, 16));
        speedNWLabel.setMinimumSize(new java.awt.Dimension(66, 16));
        speedNWLabel.setPreferredSize(new java.awt.Dimension(66, 16));
        jPanel5.add(speedNWLabel);

        speedSWLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jessy/shipgirlcombatsystem/images/ArrowSW.png"))); // NOI18N
        speedSWLabel.setText("0");
        speedSWLabel.setPreferredSize(new java.awt.Dimension(66, 18));
        jPanel5.add(speedSWLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        movementPanel.add(jPanel5, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Thrusters"));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel6.setLayout(new java.awt.GridLayout(4, 3));
        jPanel6.add(jLabel10);

        upButton1.setText("up");
        upButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(upButton1);
        jPanel6.add(jLabel11);

        jButton9.setText("side");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jPanel6.add(jLabel12);

        jButton10.setText("side");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton10);

        jButton11.setText("side");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton11);
        jPanel6.add(jLabel13);

        jButton12.setText("side");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12);
        jPanel6.add(jLabel14);

        jButton13.setText("down");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton13);
        jPanel6.add(jLabel15);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        movementPanel.add(jPanel6, gridBagConstraints);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Main Engine"));
        jPanel7.setLayout(new java.awt.GridLayout(2, 3));
        jPanel7.add(jLabel16);

        jButton14.setText("forward");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton14);
        jPanel7.add(jLabel17);

        jButton15.setText("turn Left");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton15);
        jPanel7.add(jLabel18);

        jButton16.setText("turn Right");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton16);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        movementPanel.add(jPanel7, gridBagConstraints);

        tabbedPanel.addTab("Movement", movementPanel);

        actionTabPanel.setLayout(new java.awt.GridLayout(0, 1));

        actionPanel.setBackground(new java.awt.Color(102, 102, 102));
        actionPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        actionPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 5));
        jScrollPane1.setViewportView(actionPanel);

        actionTabPanel.add(jScrollPane1);

        tabbedPanel.addTab("Actions", actionTabPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(tabbedPanel, gridBagConstraints);

        damageLabel.setForeground(new java.awt.Color(153, 0, 0));
        damageLabel.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(damageLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void upButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton1ActionPerformed
        // TODO add your handling code here:
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.NORTH));
        updateShip(currentShip);
    }//GEN-LAST:event_upButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.NORTHEAST));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.NORTHWEST));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.SOUTHEAST));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.SOUTHWEST));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        MapPanel.getInstance().addCommand(ShipCommands.drift(currentShip, Direction.SOUTH));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        MapPanel.getInstance().addCommand(ShipCommands.moveForward(currentShip));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        MapPanel.getInstance().addCommand(ShipCommands.turnLeft(currentShip));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        MapPanel.getInstance().addCommand(ShipCommands.turnRight(currentShip));
        updateShip(currentShip);
    }//GEN-LAST:event_jButton16ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel actionTabPanel;
    private javax.swing.JLabel damageLabel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel movementPanel;
    private javax.swing.JLabel shipNameField;
    private javax.swing.JLabel speedNLabel;
    private javax.swing.JLabel speedNWLabel;
    private javax.swing.JLabel speedSWLabel;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JButton upButton1;
    // End of variables declaration//GEN-END:variables
}
